SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [csci340].[CONSTELLATION](
	[Abbreviation] [char](3) NOT NULL,
	[Name] [varchar](20) NOT NULL,
	[Shape] [varchar](50) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [csci340].[CONSTELLATION] ADD  CONSTRAINT [PK_CONSTELLATION_ABBREVIATION] PRIMARY KEY CLUSTERED 
(
	[Abbreviation] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [csci340].[CONSTELLATION] ADD  CONSTRAINT [UN_CONSTELLATION_NAME] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [csci340].[CONSTELLATION]  WITH CHECK ADD  CONSTRAINT [CK_CONSTELLATION_SHAPE] CHECK  (([Shape]='SPOON' OR [Shape]=NULL))
GO
ALTER TABLE [csci340].[CONSTELLATION] CHECK CONSTRAINT [CK_CONSTELLATION_SHAPE]
GO
