SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [csci340].[STAR](
	[CatalogNumber] [varchar](10) NOT NULL,
	[Name] [varchar](20) NULL,
	[Mass] [int] NOT NULL,
	[Constellation] [char](3) NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [csci340].[STAR] ADD  CONSTRAINT [PK_STAR_CATALOGNUMBER] PRIMARY KEY CLUSTERED 
(
	[CatalogNumber] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [csci340].[STAR]  WITH CHECK ADD  CONSTRAINT [FK_STAR_CONSTELLATION] FOREIGN KEY([Constellation])
REFERENCES [csci340].[CONSTELLATION] ([Abbreviation])
GO
ALTER TABLE [csci340].[STAR] CHECK CONSTRAINT [FK_STAR_CONSTELLATION]
GO
ALTER TABLE [csci340].[STAR]  WITH CHECK ADD  CONSTRAINT [CK_STAR_MASS] CHECK  (([Mass]>(0)))
GO
ALTER TABLE [csci340].[STAR] CHECK CONSTRAINT [CK_STAR_MASS]
GO
